spin_manifest_version = 2

[application]
name = "adventofspin-2024"
version = "0.1.0"
authors = ["Thorsten Hans <thorsten.hans@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "frontend"

[[trigger.http]]
route = "/api/wishlists/..."
component = "api-wishlists"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "app", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }

[component.frontend.build]
workdir = "frontend"
command = "npm run build"

[component.api-wishlists]
source = "api-wishlists/target/wasm32-wasi/release/api_wishlists.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]

[component.api-wishlists.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "api-wishlists"
watch = ["src/**/*.rs", "Cargo.toml"]
